import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  translations: Record<string, Record<string, string>>;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.about': 'About',
    'nav.clients': 'Clients',
    'nav.contact': 'Contact',
    'nav.getStarted': 'Get Started',
    
    // Hero section
    'hero.subtitle': 'Simplifying Technology,',
    'hero.title': 'Empowering Solutions',
    'hero.description': 'Dataproxy Enterprise delivers cutting-edge data management solutions and IT services that transform how businesses leverage their information assets.',
    'hero.solutions': 'Our Solutions',
    'hero.contact': 'Contact Us',
    'hero.trusted': 'Trusted by industry leaders:',
    
    // Services section
    'services.title': 'Our Enterprise Solutions',
    'services.description': 'Dataproxy Enterprise offers a comprehensive suite of services designed to optimize your data infrastructure and drive business growth.',
    'services.dataManagement': 'Management System',
    'services.dataManagement.desc': 'Solution designed to streamline your business operations, enhance productivity, and improve decision-making by integrating and automating key processes across your organization',
    'services.cloudSolutions': 'Software Development',
    'services.cloudSolutions.desc': 'Custom software development solutions designed to meet your unique business needs, delivering high-quality, scalable, and efficient applications that drive growth and innovation',
    'services.cybersecurity': 'IT Consulting and Support',
    'services.cybersecurity.desc': 'Expert IT consulting and support services to optimize your technology infrastructure, ensuring seamless operations, strategic planning, and robust solutions for business success.',
    'services.enterpriseSoftware': 'Website Hosting',
    'services.enterpriseSoftware.desc': 'Reliable website hosting services offering fast, secure, and scalable solutions to ensure your website runs smoothly, with minimal downtime and maximum performance.',
    'services.businessIntelligence': 'Sale of Computer Equipment',
    'services.businessIntelligence.desc': 'High-quality computer equipment sales offering the latest technology and reliable hardware solutions to meet your business and personal computing needs.',
    'services.itConsulting': 'Website Creation',
    'services.itConsulting.desc': 'Professional website creation services to build visually appealing, user-friendly, and responsive websites tailored to your business needs, ensuring an exceptional online presence.',
    'services.learnMore': 'Learn More',
    'services.backToServices': 'Back to Services',
    'services.keyFeatures': 'Key Features',
    'about.backToHome': 'Back to Home',
    
    // About section
    'about.title': 'About Dataproxy Enterprise',
    'about.p1': 'Dataproxy is a company established in Mozambique, dedicated to driving the development and growth of its clients through innovative solutions in the field of Information Technology (IT) as well as selling computer equipment.',
    'about.p2': 'Our mission is to provide services and products that not only meet but also exceed market expectations, thus contributing to advancement and excellence in all our operations.',
    'about.learnMore': 'Learn More',
    'features.security': 'Market-leading data security protocols',
    'features.team': 'Experienced team of IT professionals',
    'features.solutions': 'Customized business solutions',
    'features.support': 'Dedicated 24/7 technical support',
    'features.innovation': 'Continuous innovation and improvement',
    'features.global': 'Global service delivery capabilities',
    
    // Contact section
    'contact.title': 'Get in Touch',
    'contact.description': 'Contact our team for information about our services or to request a custom quote.',
    'contact.getInTouch': 'Get in Touch',
    'contact.form.title': 'Send Us a Message',
    'contact.form.name': 'Name',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Subject',
    'contact.form.subject.placeholder': 'How can we help you?',
    'contact.form.message': 'Message',
    'contact.form.message.placeholder': 'Tell us about your project...',
    'contact.form.send': 'Send Message',
    'contact.info.title': 'Contact Information',
    'contact.info.visit': 'Visit Us',
    'contact.info.call': 'Call Us',
    'contact.info.email': 'Email Us',
    'contact.info.hours': 'Business Hours',
    'contact.info.weekdays': 'Monday - Friday: 7:00 AM - 5:00 PM',
    'contact.info.saturday': 'Saturday: 8:00 AM - 12:00 PM',
    'contact.info.sunday': 'Sunday: Closed',

    // Service Details - Data Management
    'services.dataManagement.full': 'Our services encompass the provision of complete management systems, meticulously designed to meet the specific needs of companies in diverse sectors, including billing, human resources, accounting, inventory management and procurement. These solutions are designed based on a deep understanding of the challenges faced by our customers, aiming to offer efficiency, precision and control at all stages of the process.',
    'services.dataManagement.salesSystem': 'Sales System',
    'services.dataManagement.salesSystemDesc': 'Increase your sales and improve the customer experience with comprehensive tools to manage leads, opportunities, quotes and orders.',
    'services.dataManagement.inventory': 'Inventory Management',
    'services.dataManagement.inventoryDesc': 'Optimize your inventory with precise stock control, real-time tracking, and automatic replenishment alerts.',
    'services.dataManagement.accounting': 'Accounting',
    'services.dataManagement.accountingDesc': 'Simplify accounting processes with an integrated system that manages financial reports, reconciliations, and tax compliance.',
    'services.dataManagement.hr': 'Human Resources',
    'services.dataManagement.hrDesc': 'Manage the entire employee lifecycle, from recruitment to retirement, with tools for payroll, vacations, and evaluations.',
    'services.dataManagement.benefits': 'Benefits',
    'services.dataManagement.benefit1': 'Customized solutions for your specific requirements',
    'services.dataManagement.benefit2': 'Seamless integration between all business modules',
    'services.dataManagement.benefit3': 'Intuitive and easy-to-use interfaces',
    'services.dataManagement.benefit4': 'Ongoing technical support and training for your team',
    'services.dataManagement.transformation': 'How Our Management System Can Transform Your Business',
    'services.dataManagement.dataCentralization': 'Data Centralization',
    'services.dataManagement.dataCentralizationDesc': 'Eliminate information silos and centralize all critical data in a single platform, providing a holistic view of your business and facilitating strategic decision-making.',
    'services.dataManagement.dashboards': 'Dashboards and Reports',
    'services.dataManagement.dashboardsDesc': 'Access interactive dashboards and detailed reports to monitor business performance in real-time, identify trends, and easily detect opportunities for improvement.',
    'services.dataManagement.automation': 'Automation',
    'services.dataManagement.automationDesc': 'Automate repetitive manual processes to increase efficiency, reduce errors, and allow your team to focus on strategic activities that add more value to the business.',
    
    // Service Details - Software Development
    'services.cloudSolutions.full': "Our custom software development services are designed to create tailored digital solutions that meet your specific business needs. From mobile apps to enterprise-level systems, we combine cutting-edge technology with innovative design to deliver software that enhances efficiency, improves user experience, and drives your business forward.",
    'services.cloudSolutions.feature1': 'Web and mobile application development',
    'services.cloudSolutions.feature2': 'Custom enterprise software solutions',
    'services.cloudSolutions.feature3': 'Software integration and API development',
    'services.cloudSolutions.technologies': 'Technologies We Use',
    'services.cloudSolutions.database': 'Database',
    
    // Service Details - IT Consulting
    'services.cybersecurity.full': 'Our IT consulting and support services provide comprehensive technological assistance to optimize your business operations. Our team of experienced professionals offers strategic guidance, technical support, and innovative solutions to address your IT challenges, ensure system reliability, and drive digital transformation.',
    'services.cybersecurity.feature1': 'IT infrastructure assessment and planning',
    'services.cybersecurity.feature2': 'Technical support and problem resolution',
    'services.cybersecurity.feature3': 'Technology strategy and digital transformation',
    'services.cybersecurity.services': 'Services Offered',
    'services.cybersecurity.strategicConsulting': 'Strategic Consulting',
    'services.cybersecurity.consultingDesc': 'Infrastructure assessment, technology planning, and business alignment with objectives.',
    'services.cybersecurity.techSupport': 'Technical Support',
    'services.cybersecurity.techSupportDesc': 'Remote and on-site support for problem resolution, preventive and corrective maintenance.',
    'services.cybersecurity.optimization': 'Systems Optimization',
    'services.cybersecurity.optimizationDesc': 'Performance analysis, implementation of improvements, and recommendations for increased efficiency.',
    'services.cybersecurity.training': 'Training',
    'services.cybersecurity.trainingDesc': 'Training your team to efficiently use the implemented technology solutions.',
    'services.cybersecurity.benefits': 'Benefits',
    'services.cybersecurity.benefit1': 'Reduced operational costs and downtime',
    'services.cybersecurity.benefit2': 'Increased productivity and process efficiency',
    'services.cybersecurity.benefit3': 'Access to specialized knowledge without the need for hiring',
    'services.cybersecurity.benefit4': 'Focus on your core business while we take care of your IT',
    'services.cybersecurity.supportPlans': 'Our Support Plans',
    'services.cybersecurity.basic': 'Basic',
    'services.cybersecurity.business': 'Business',
    'services.cybersecurity.premium': 'Premium',
    'services.cybersecurity.contactForPrice': 'Contact for Price',
    'services.cybersecurity.getQuote': 'Request a Quote',
    'services.cybersecurity.mostPopular': 'Most Popular',
    'services.cybersecurity.basicFeature1': 'Remote support during business hours',
    'services.cybersecurity.basicFeature2': 'Response time within 24 hours',
    'services.cybersecurity.basicFeature3': 'Basic monitoring',
    'services.cybersecurity.basicFeature4': 'Monthly reports',
    'services.cybersecurity.businessFeature1': 'Remote and on-site support',
    'services.cybersecurity.businessFeature2': 'Response time within 4 hours',
    'services.cybersecurity.businessFeature3': 'Advanced 24/7 monitoring',
    'services.cybersecurity.businessFeature4': 'Monthly consulting',
    'services.cybersecurity.businessFeature5': 'Managed backup',
    'services.cybersecurity.premiumFeature1': 'Priority 24/7 support',
    'services.cybersecurity.premiumFeature2': 'Response time within 1 hour',
    'services.cybersecurity.premiumFeature3': 'Proactive monitoring',
    'services.cybersecurity.premiumFeature4': 'Weekly consulting',
    'services.cybersecurity.premiumFeature5': 'Project management',
    'services.cybersecurity.premiumFeature6': 'Disaster recovery',
    
    // Service Details - Website Hosting
    'services.enterpriseSoftware.full': 'We offer reliable website hosting services with high availability and robust performance. Our redundant infrastructure ensures your site stays online and accessible 24 hours a day, 7 days a week, with dedicated technical support and constant monitoring.',
    'services.enterpriseSoftware.feature1': 'High-performance server hosting with 99.9% uptime',
    'services.enterpriseSoftware.feature2': 'Free SSL certificates to ensure your website security',
    'services.enterpriseSoftware.feature3': 'Automated daily backup and malware protection',
    'services.enterpriseSoftware.feature4': '24/7 technical support and intuitive control panel',
    'services.enterpriseSoftware.plans': 'Our Plans',
    'services.enterpriseSoftware.basic': 'Basic',
    'services.enterpriseSoftware.basicDesc': 'Ideal for personal websites and small businesses',
    'services.enterpriseSoftware.business': 'Business',
    'services.enterpriseSoftware.businessDesc': 'For corporate sites with medium traffic',
    'services.enterpriseSoftware.premium': 'Premium',
    'services.enterpriseSoftware.premiumDesc': 'Scalable solutions for e-commerce and web applications',
    'services.enterpriseSoftware.dedicated': 'Dedicated',
    'services.enterpriseSoftware.dedicatedDesc': 'Dedicated servers for maximum performance',
    'services.enterpriseSoftware.whyChoose': 'Why choose our hosting services?',
    'services.enterpriseSoftware.performance': 'Superior Performance',
    'services.enterpriseSoftware.performanceDesc': 'We use cutting-edge technology to ensure your websites load quickly and operate efficiently. Our servers are optimized to provide fast response times and a seamless user experience for your visitors.',
    'services.enterpriseSoftware.security': 'Advanced Security',
    'services.enterpriseSoftware.securityDesc': 'We protect your site against threats with advanced firewalls, DDoS protection, regular security checks, and free SSL certificates. Your peace of mind is our priority.',
    'services.enterpriseSoftware.support': 'Expert Support',
    'services.enterpriseSoftware.supportDesc': 'Our technical support team is available 24/7 to help with any issues or questions. We offer personalized assistance to ensure your website is always working perfectly.',
    'services.enterpriseSoftware.scalability': 'Scalability',
    'services.enterpriseSoftware.scalabilityDesc': 'As your business grows, your hosting resources can be easily scaled. Our flexible solutions allow you to increase resources as needed, without service interruptions.',
    
    // Service Details - Computer Equipment Sales
    'services.businessIntelligence.full': 'Dataproxy offers a wide range of high-quality computer equipment, from computers and laptops to peripherals and accessories. We work with leading brands in the market to ensure that your business or personal use has access to the best available technology, with competitive prices and specialized technical support.',
    'services.businessIntelligence.catalog': 'Our Catalog',
    'services.businessIntelligence.computers': 'Computers and Laptops',
    'services.businessIntelligence.computersDesc': 'Workstations, business laptops, and personal computers from recognized brands.',
    'services.businessIntelligence.monitors': 'Monitors and Peripherals',
    'services.businessIntelligence.monitorsDesc': 'High-definition monitors, keyboards, mice, webcams, and other accessories to improve your productivity.',
    'services.businessIntelligence.printers': 'Printers and Multifunction Devices',
    'services.businessIntelligence.printersDesc': 'Equipment for printing, scanning, and copying for office environments of any size.',
    'services.businessIntelligence.network': 'Network Equipment',
    'services.businessIntelligence.networkDesc': 'Routers, switches, access points, and all necessary infrastructure for your connectivity.',
    'services.businessIntelligence.whyChooseUs': 'Why Buy From Us',
    'services.businessIntelligence.warranty': 'Original products with factory warranty',
    'services.businessIntelligence.consultation': 'Consultation in choosing the ideal equipment for your need',
    'services.businessIntelligence.support': 'Post-sale technical support',
    'services.businessIntelligence.installation': 'Equipment installation and configuration (optional service)',
    'services.businessIntelligence.partners': 'Partner Brands',
    'services.businessIntelligence.featured': 'Featured Products',
    'services.businessIntelligence.businessLaptops': 'Business Laptops',
    'services.businessIntelligence.businessLaptopsDesc': 'Robust and reliable equipment to increase your team\'s productivity.',
    'services.businessIntelligence.storage': 'Storage Solutions',
    'services.businessIntelligence.storageDesc': 'HDDs, SSDs, and NAS systems for secure storage of your data.',
    'services.businessIntelligence.servers': 'Servers',
    'services.businessIntelligence.serversDesc': 'Robust infrastructure to host your critical applications and services.',
    
    // Service Details - Website Creation
    'services.itConsulting.full': 'Dataproxy offers comprehensive website creation services, from design and development to implementation and maintenance. Our specialists create responsive, attractive, and optimized sites that reflect your brand identity and help achieve your online business goals. Whether a simple corporate site or a complex e-commerce platform, we deliver customized solutions to meet your specific needs.',
    'services.itConsulting.types': 'Website Types',
    'services.itConsulting.corporate': 'Corporate Sites',
    'services.itConsulting.corporateDesc': 'Present your company and services with a professional and elegant site.',
    'services.itConsulting.ecommerce': 'E-commerce',
    'services.itConsulting.ecommerceDesc': 'Sell your products online with a complete and secure e-commerce platform.',
    'services.itConsulting.webPortals': 'Web Portals and Systems',
    'services.itConsulting.webPortalsDesc': 'Automate processes with custom web systems for your business.',
    'services.itConsulting.landingPages': 'Landing Pages',
    'services.itConsulting.landingPagesDesc': 'Capture leads and promote specific products with optimized conversion pages.',
    'services.itConsulting.included': 'What We Include',
    'services.itConsulting.design': 'Responsive and customized design',
    'services.itConsulting.seo': 'Search engine optimization (SEO)',
    'services.itConsulting.socialMedia': 'Social media integration',
    'services.itConsulting.cms': 'Content management system (CMS)',
    'services.itConsulting.hosting': 'Hosting and domain (optional)',
    'services.itConsulting.support': 'Technical support and maintenance',
    'services.itConsulting.process': 'Our Development Process',
    'services.itConsulting.brief': 'Briefing and Planning',
    'services.itConsulting.briefDesc': 'We understand your needs and objectives to create a strategic plan.',
    'services.itConsulting.prototype': 'Design and Prototype',
    'services.itConsulting.prototypeDesc': 'We create layouts and wireframes for visualization and approval before development.',
    'services.itConsulting.development': 'Development',
    'services.itConsulting.developmentDesc': 'We program your site with the best technologies and coding practices.',
    'services.itConsulting.launch': 'Launch and Support',
    'services.itConsulting.launchDesc': 'We publish your site and offer ongoing support to ensure your online success.',
    'services.itConsulting.technologies': 'Technologies We Use',
  },
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.services': 'Serviços',
    'nav.about': 'Sobre',
    'nav.clients': 'Clientes',
    'nav.contact': 'Contato',
    'nav.getStarted': 'Começar',
    
    // Hero section
    'hero.subtitle': 'Simplificando a Tecnologia,',
    'hero.title': 'Potencializando Soluções',
    'hero.description': 'A Dataproxy Enterprise oferece soluções de gestão de dados de ponta e serviços de TI que transformam a forma como as empresas aproveitam seus ativos de informaç��o.',
    'hero.solutions': 'Nossas Soluções',
    'hero.contact': 'Contacte-nos',
    'hero.trusted': 'Confiado por líderes da indústria:',
    
    // Services section
    'services.title': 'Nossas Soluções Empresariais',
    'services.description': 'A Dataproxy Enterprise oferece um conjunto abrangente de serviços projetados para otimizar sua infraestrutura de dados e impulsionar o crescimento dos negócios.',
    'services.dataManagement': 'Sistema de Gestão',
    'services.dataManagement.desc': 'Solução projetada para simplificar suas operações comerciais, aumentar a produtividade e melhorar a tomada de decisões integrando e automatizando processos-chave em toda a sua organização.',
    'services.cloudSolutions': 'Desenvolvimento de Software',
    'services.cloudSolutions.desc': 'Soluções personalizadas de desenvolvimento de software projetadas para atender às necessidades exclusivas do seu negócio, entregando aplicações de alta qualidade, escaláveis e eficientes que impulsionam o crescimento e a inovação.',
    'services.cybersecurity': 'Consultoria e Suporte de TI',
    'services.cybersecurity.desc': 'Serviços especializados de consultoria e suporte em TI para otimizar sua infraestrutura tecnológica, garantindo operações perfeitas, planejamento estratégico e soluções robustas para o sucesso do negócio.',
    'services.enterpriseSoftware': 'Hospedagem de Website',
    'services.enterpriseSoftware.desc': 'Serviços confiáveis de hospedagem de websites oferecendo soluções rápidas, seguras e escaláveis para garantir que seu site funcione sem problemas, com tempo mínimo de inatividade e desempenho máximo.',
    'services.businessIntelligence': 'Venda de Equipamento Informático',
    'services.businessIntelligence.desc': 'Venda de equipamentos informáticos de alta qualidade oferecendo tecnologia de ponta e soluções de hardware confiáveis para atender às suas necessidades empresariais e de computação pessoal.',
    'services.itConsulting': 'Criação de Website',
    'services.itConsulting.desc': 'Serviços profissionais de criação de websites para construir sites visualmente atraentes, amigáveis ao usuário e responsivos, adaptados às necessidades do seu negócio, garantindo uma presença online excepcional.',
    'services.learnMore': 'Saiba Mais',
    'services.backToServices': 'Voltar para Serviços',
    'services.keyFeatures': 'Principais Recursos',
    'about.backToHome': 'Voltar para Página Inicial',
    
    // About section
    'about.title': 'Sobre a Dataproxy Enterprise',
    'about.p1': 'A Dataproxy é uma empresa estabelecida em Moçambique, dedicada a impulsionar o desenvolvimento e crescimento de seus clientes por meio de soluções inovadoras no campo da Tecnologia da Informação (TI) assim como venda de equipamentos informáticos.',
    'about.p2': 'Nossa missão é proporcionar serviços e produtos que não apenas atendam, mas também superem as expectativas do mercado, contribuindo assim para o avanço e a excelência em todas as nossas operações.',
    'about.learnMore': 'Saiba Mais',
    'features.security': 'Protocolos de segurança de dados líderes de mercado',
    'features.team': 'Equipe experiente de profissionais de TI',
    'features.solutions': 'Soluções empresariais personalizadas',
    'features.support': 'Suporte técnico dedicado 24/7',
    'features.innovation': 'Inovação e melhoria contínuas',
    'features.global': 'Capacidades de entrega de serviços globais',
    
    // Contact section
    'contact.title': 'Entre em Contato',
    'contact.description': 'Entre em contato com nossa equipe para obter informações sobre nossos serviços ou solicitar um orçamento personalizado.',
    'contact.getInTouch': 'Entre em Contato',
    'contact.form.title': 'Envie-nos uma Mensagem',
    'contact.form.name': 'Nome',
    'contact.form.email': 'E-mail',
    'contact.form.subject': 'Assunto',
    'contact.form.subject.placeholder': 'Como podemos ajudá-lo?',
    'contact.form.message': 'Mensagem',
    'contact.form.message.placeholder': 'Conte-nos sobre seu projeto...',
    'contact.form.send': 'Enviar Mensagem',
    'contact.info.title': 'Informações de Contato',
    'contact.info.visit': 'Visite-nos',
    'contact.info.call': 'Ligue para nós',
    'contact.info.email': 'E-mail',
    'contact.info.hours': 'Horário de Funcionamento',
    'contact.info.weekdays': 'Segunda - Sexta: 7:00 - 17:00',
    'contact.info.saturday': 'Sábado: 8:00 - 12:00',
    'contact.info.sunday': 'Domingo: Fechado',
    
    // Service Details - Data Management
    'services.dataManagement.full': 'Nossos serviços abrangem o fornecimento de sistemas de gestão completos, meticulosamente projetados para atender às necessidades específicas de empresas em diversos setores, incluindo faturamento, recursos humanos, contabilidade, gestão de inventário e compras. Essas soluções são projetadas com base em uma compreensão profunda dos desafios enfrentados pelos nossos clientes, visando oferecer eficiência, precisão e controle em todas as etapas do processo.',
    'services.dataManagement.salesSystem': 'Sistema de Vendas',
    'services.dataManagement.salesSystemDesc': 'Aumente suas vendas e melhore a experiência do cliente com ferramentas abrangentes para gerenciar leads, oportunidades, cotações e pedidos.',
    'services.dataManagement.inventory': 'Gestão de Estoque',
    'services.dataManagement.inventoryDesc': 'Otimize seu inventário com controle preciso de estoque, rastreamento em tempo real, e alertas automáticos de reposição.',
    'services.dataManagement.accounting': 'Contabilidade',
    'services.dataManagement.accountingDesc': 'Simplifique processos contábeis com um sistema integrado que gerencia relatórios financeiros, conciliações e conformidade fiscal.',
    'services.dataManagement.hr': 'Recursos Humanos',
    'services.dataManagement.hrDesc': 'Gerencie todo o ciclo de vida do funcionário, desde o recrutamento até a aposentadoria, com ferramentas para folha de pagamento, férias e avaliações.',
    'services.dataManagement.benefits': 'Benefícios',
    'services.dataManagement.benefit1': 'Soluções personalizadas para seus requisitos específicos',
    'services.dataManagement.benefit2': 'Integração perfeita entre todos os módulos de negócios',
    'services.dataManagement.benefit3': 'Interfaces intuitivas e fáceis de usar',
    'services.dataManagement.benefit4': 'Suporte técnico contínuo e treinamento para sua equipe',
    'services.dataManagement.transformation': 'Como Nosso Sistema de Gestão Pode Transformar Seu Negócio',
    'services.dataManagement.dataCentralization': 'Centralização de Dados',
    'services.dataManagement.dataCentralizationDesc': 'Elimine silos de informação e centralize todos os dados críticos em uma única plataforma, proporcionando uma visão holística do seu negócio e facilitando a tomada de decisões estratégicas.',
    'services.dataManagement.dashboards': 'Painéis e Relatórios',
    'services.dataManagement.dashboardsDesc': 'Acesse painéis interativos e relatórios detalhados para monitorar o desempenho do negócio em tempo real, identificar tendências e detectar oportunidades de melhoria com facilidade.',
    'services.dataManagement.automation': 'Automação',
    'services.dataManagement.automationDesc': 'Automatize processos manuais repetitivos para aumentar a eficiência, reduzir erros, e permitir que sua equipe se concentre em atividades estratégicas que agregam mais valor ao negócio.',
    
    // Service Details - Software Development
    'services.cloudSolutions.full': 'Nossos serviços de desenvolvimento de software personalizado são projetados para criar soluções digitais sob medida que atendam às necessidades específicas do seu negócio. De aplicativos móveis a sistemas de nível empresarial, combinamos tecnologia de ponta com design inovador para entregar software que melhora a eficiência, aprimora a experiência do usuário e impulsiona seu negócio.',
    'services.cloudSolutions.feature1': 'Desenvolvimento de aplicações web e mobile',
    'services.cloudSolutions.feature2': 'Soluções de software empresarial personalizadas',
    'services.cloudSolutions.feature3': 'Integração de software e desenvolvimento de API',
    'services.cloudSolutions.technologies': 'Tecnologias que Utilizamos',
    'services.cloudSolutions.database': 'Banco de Dados',
    
    // Service Details - IT Consulting
    'services.cybersecurity.full': 'A Dataproxy oferece serviços completos de consultoria e suporte em TI para garantir que sua infraestrutura tecnológica funcione perfeitamente e esteja alinhada com os objetivos do seu negócio. Nossa equipe de especialistas está pronta para ajudar sua organização a maximizar o retorno sobre o investimento em tecnologia, minimizando riscos e otimizando processos.',
    'services.cybersecurity.feature1': 'Avaliação e planejamento da infraestrutura de TI',
    'services.cybersecurity.feature2': 'Suporte técnico e resolução de problemas',
    'services.cybersecurity.feature3': 'Estratégia de tecnologia e transformação digital',
    'services.cybersecurity.services': 'Serviços Oferecidos',
    'services.cybersecurity.strategicConsulting': 'Consultoria Estratégica',
    'services.cybersecurity.consultingDesc': 'Avaliação de infraestrutura, planejamento tecnológico e alinhamento com objetivos de negócios.',
    'services.cybersecurity.techSupport': 'Suporte Técnico',
    'services.cybersecurity.techSupportDesc': 'Suporte remoto e presencial para resolução de problemas, manutenção preventiva e corretiva.',
    'services.cybersecurity.optimization': 'Otimização de Sistemas',
    'services.cybersecurity.optimizationDesc': 'Análise de desempenho, implementação de melhorias e recomendações para aumento de eficiência.',
    'services.cybersecurity.training': 'Treinamento',
    'services.cybersecurity.trainingDesc': 'Capacitação da sua equipe para utilizar eficientemente as soluções tecnológicas implementadas.',
    'services.cybersecurity.benefits': 'Benefícios',
    'services.cybersecurity.benefit1': 'Redução de custos operacionais e tempos de inatividade',
    'services.cybersecurity.benefit2': 'Aumento da produtividade e eficiência de processos',
    'services.cybersecurity.benefit3': 'Acesso a conhecimento especializado sem necessidade de contratações',
    'services.cybersecurity.benefit4': 'Foco no seu core business enquanto cuidamos da sua TI',
    'services.cybersecurity.supportPlans': 'Nossos Planos de Suporte',
    'services.cybersecurity.basic': 'Básico',
    'services.cybersecurity.business': 'Empresarial',
    'services.cybersecurity.premium': 'Premium',
    'services.cybersecurity.contactForPrice': 'Sob Consulta',
    'services.cybersecurity.getQuote': 'Solicitar Orçamento',
    'services.cybersecurity.mostPopular': 'Mais Popular',
    'services.cybersecurity.basicFeature1': 'Suporte remoto em horário comercial',
    'services.cybersecurity.basicFeature2': 'Tempo de resposta em até 24 horas',
    'services.cybersecurity.basicFeature3': 'Monitoramento básico',
    'services.cybersecurity.basicFeature4': 'Relatórios mensais',
    'services.cybersecurity.businessFeature1': 'Suporte remoto e presencial',
    'services.cybersecurity.businessFeature2': 'Tempo de resposta em até 4 horas',
    'services.cybersecurity.businessFeature3': 'Monitoramento avançado 24/7',
    'services.cybersecurity.businessFeature4': 'Consultoria mensal',
    'services.cybersecurity.businessFeature5': 'Backup gerenciado',
    'services.cybersecurity.premiumFeature1': 'Suporte prioritário 24/7',
    'services.cybersecurity.premiumFeature2': 'Tempo de resposta em até 1 hora',
    'services.cybersecurity.premiumFeature3': 'Monitoramento proativo',
    'services.cybersecurity.premiumFeature4': 'Consultoria semanal',
    'services.cybersecurity.premiumFeature5': 'Gerenciamento de projetos',
    'services.cybersecurity.premiumFeature6': 'Recuperação de desastres',
    
    // Service Details - Website Hosting
    'services.enterpriseSoftware.full': 'Oferecemos serviços de hospedagem de websites confiáveis, com alta disponibilidade e desempenho robusto. Nossa infraestrutura redundante garante que seu site permaneça online e acessível 24 horas por dia, 7 dias por semana, com suporte técnico dedicado e monitoramento constante.',
    'services.enterpriseSoftware.feature1': 'Hospedagem em servidores de alto desempenho com 99.9% de uptime',
    'services.enterpriseSoftware.feature2': 'Certificados SSL gratuitos para garantir a segurança do seu website',
    'services.enterpriseSoftware.feature3': 'Backup diário automatizado e proteção contra malware',
    'services.enterpriseSoftware.feature4': 'Suporte técnico 24/7 e painel de controle intuitivo',
    'services.enterpriseSoftware.plans': 'Nossos Planos',
    'services.enterpriseSoftware.basic': 'Básico',
    'services.enterpriseSoftware.basicDesc': 'Ideal para sites pessoais e pequenos negócios',
    'services.enterpriseSoftware.business': 'Empresarial',
    'services.enterpriseSoftware.businessDesc': 'Para sites corporativos com tráfego médio',
    'services.enterpriseSoftware.premium': 'Premium',
    'services.enterpriseSoftware.premiumDesc': 'Soluções escaláveis para e-commerce e aplicações web',
    'services.enterpriseSoftware.dedicated': 'Dedicado',
    'services.enterpriseSoftware.dedicatedDesc': 'Servidores dedicados para máximo desempenho',
    'services.enterpriseSoftware.whyChoose': 'Por que escolher nossos serviços de hospedagem?',
    'services.enterpriseSoftware.performance': 'Desempenho Superior',
    'services.enterpriseSoftware.performanceDesc': 'Utilizamos tecnologia de ponta para garantir que seus websites carreguem rapidamente e operem com eficiência. Nossos servidores são otimizados para fornecer tempos de resposta rápidos e uma experiência de usuário impecável para seus visitantes.',
    'services.enterpriseSoftware.security': 'Segurança Avançada',
    'services.enterpriseSoftware.securityDesc': 'Protegemos seu site contra ameaças com firewalls avançados, proteção contra DDoS, verificações regulares de segurança e certificados SSL gratuitos. Sua tranquilidade é nossa prioridade.',
    'services.enterpriseSoftware.support': 'Suporte Especializado',
    'services.enterpriseSoftware.supportDesc': 'Nossa equipe de suporte técnico está disponível 24/7 para ajudar com qualquer problema ou dúvida. Oferecemos assistência personalizada para garantir que seu website esteja sempre funcionando perfeitamente.',
    'services.enterpriseSoftware.scalability': 'Escalabilidade',
    'services.enterpriseSoftware.scalabilityDesc': 'À medida que seu negócio cresce, seus recursos de hospedagem podem ser facilmente escalados. Nossas soluções flexíveis permitem que você aumente recursos conforme necessário, sem interrupções no serviço.',
    
    // Service Details - Computer Equipment Sales
    'services.businessIntelligence.full': 'A Dataproxy oferece uma ampla gama de equipamentos informáticos de alta qualidade, desde computadores e laptops até periféricos e acessórios. Trabalhamos com as principais marcas do mercado para garantir que sua empresa ou uso pessoal tenha acesso à melhor tecnologia disponível, com preços competitivos e suporte técnico especializado.',
    'services.businessIntelligence.catalog': 'Nosso Catálogo',
    'services.businessIntelligence.computers': 'Computadores e Laptops',
    'services.businessIntelligence.computersDesc': 'Estações de trabalho, laptops empresariais e computadores para uso pessoal de marcas reconhecidas.',
    'services.businessIntelligence.monitors': 'Monitores e Periféricos',
    'services.businessIntelligence.monitorsDesc': 'Monitores de alta definição, teclados, mouses, webcams e outros acessórios para melhorar sua produtividade.',
    'services.businessIntelligence.printers': 'Impressoras e Multifuncionais',
    'services.businessIntelligence.printersDesc': 'Equipamentos para impressão, digitalização e cópia para ambientes de escritório de qualquer porte.',
    'services.businessIntelligence.network': 'Equipamentos de Rede',
    'services.businessIntelligence.networkDesc': 'Roteadores, switches, pontos de acesso e toda infraestrutura necessária para sua conectividade.',
    'services.businessIntelligence.whyChooseUs': 'Por Que Comprar Conosco',
    'services.businessIntelligence.warranty': 'Produtos originais com garantia de fábrica',
    'services.businessIntelligence.consultation': 'Consultoria na escolha do equipamento ideal para sua necessidade',
    'services.businessIntelligence.support': 'Suporte técnico pós-venda',
    'services.businessIntelligence.installation': 'Instalação e configuração dos equipamentos (serviço opcional)',
    'services.businessIntelligence.partners': 'Marcas Parceiras',
    'services.businessIntelligence.featured': 'Produtos em Destaque',
    'services.businessIntelligence.businessLaptops': 'Laptops Empresariais',
    'services.businessIntelligence.businessLaptopsDesc': 'Equipamentos robustos e confiáveis para aumentar a produtividade da sua equipe.',
    'services.businessIntelligence.storage': 'Soluções de Armazenamento',
    'services.businessIntelligence.storageDesc': 'HDDs, SSDs e sistemas NAS para armazenamento seguro dos seus dados.',
    'services.businessIntelligence.servers': 'Servidores',
    'services.businessIntelligence.serversDesc': 'Infraestrutura robusta para hospedar seus aplicativos e serviços críticos.',
    
    // Service Details - Website Creation
    'services.itConsulting.full': 'A Dataproxy oferece serviços completos de criação de websites, desde o design e desenvolvimento até a implementação e manutenção. Nossos especialistas criam sites responsivos, atraentes e otimizados que refletem a identidade da sua marca e ajudam a alcançar seus objetivos de negócio online. Seja um site institucional simples ou uma plataforma de e-commerce complexa, entregamos soluções personalizadas para atender às suas necessidades específicas.',
    'services.itConsulting.types': 'Tipos de Websites',
    'services.itConsulting.corporate': 'Sites Institucionais',
    'services.itConsulting.corporateDesc': 'Apresente sua empresa e serviços com um site profissional e elegante.',
    'services.itConsulting.ecommerce': 'Lojas Virtuais',
    'services.itConsulting.ecommerceDesc': 'Venda seus produtos online com uma plataforma de e-commerce completa e segura.',
    'services.itConsulting.webPortals': 'Portais e Sistemas Web',
    'services.itConsulting.webPortalsDesc': 'Automatize processos com sistemas web personalizados para seu negócio.',
    'services.itConsulting.landingPages': 'Landing Pages',
    'services.itConsulting.landingPagesDesc': 'Capture leads e promova produtos específicos com páginas de conversão otimizadas.',
    'services.itConsulting.included': 'O Que Incluímos',
    'services.itConsulting.design': 'Design personalizado e responsivo',
    'services.itConsulting.seo': 'Otimização para mecanismos de busca (SEO)',
    'services.itConsulting.socialMedia': 'Integração com redes sociais',
    'services.itConsulting.cms': 'Sistema de gerenciamento de conteúdo (CMS)',
    'services.itConsulting.hosting': 'Hospedagem e domínio (opcional)',
    'services.itConsulting.support': 'Suporte técnico e manutenção',
    'services.itConsulting.process': 'Nosso Processo de Desenvolvimento',
    'services.itConsulting.brief': 'Briefing e Planejamento',
    'services.itConsulting.briefDesc': 'Compreendemos suas necessidades e objetivos para criar um plano estratégico.',
    'services.itConsulting.prototype': 'Design e Protótipo',
    'services.itConsulting.prototypeDesc': 'Criamos layouts e wireframes para visualização e aprovação antes do desenvolvimento.',
    'services.itConsulting.development': 'Desenvolvimento',
    'services.itConsulting.developmentDesc': 'Programamos seu site com as melhores tecnologias e práticas de codificação.',
    'services.itConsulting.launch': 'Lançamento e Suporte',
    'services.itConsulting.launchDesc': 'Publicamos seu site e oferecemos suporte contínuo para garantir seu sucesso online.',
    'services.itConsulting.technologies': 'Tecnologias que Utilizamos',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{children: ReactNode}> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pt'); // Default language is Portuguese

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, translations, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
